baseURL: "https://blog.sreekaran.com/"
title: Sreekaran's Blog
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-12H0FM6N36

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sreekaran's Blog
  description: "Software Engineer by day, Developer Advocate by night."
  keywords: [Blog, Portfolio, Sreekaran, Srinath, Engineer, Advocate, Developer, Software, DevOps, Backend, Frontend, Fullstack, Devrel]
  author: Sreekaran
  # author: ["Me", "You"] # multiple authors
  images: ["https://sreekaran.com/assets/artpfp-1.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"

  label:
    text: "Sreekaran's Blog"
    # icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Sreekaran
    subtitle: "Software Engineer by day, Developer Advocate by night."
    imageUrl: "https://sreekaran.com/assets/artpfp-1.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: headshot
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Sreekaran \U0001F44B"
    Content: "Software Engineer by day, Developer Advocate by night.

      \nI'm using this blog as an outlet to ramble on about CS, learning, devrel, [anime](https://sreekaran.com/mal), lifting, books, and anything else that piques my curiosity.

      \nIf you want to reach out, my [Twitter](https://sreekaran.com/twt) is the right place to head to."

  socialIcons:
    - name: twitter
      url: "https://sreekaran.com/twt"
    - name: website
      url: "https://sreekaran.com"
    - name: github
      url: "https://sreekaran.com/gh"
    - name: linkedin
      url: "https://sreekaran.com/li"
    - name: instagram
      url: "https://sreekaran.com/ig"
    - name: email
      url: "mailto:hi@sreekaran.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: website
      name: sreekaran.com
      url: https://sreekaran.com
      weight: 40
    - identifier: repository
      name: repo
      url: https://github.com/sreekaransrinath/blog
      weight: 30
